cocoon/homePage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homePage'
urlpatterns = [
    url(r'^$', views.LandingPage.as_view(), name='index'),
]

cocoon/survey/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'rentSurvey', views.RentSurveyViewSet, base_name='user_survey')
router.register(r'rentSurveyAgent', views.RentSurveyAgentViewSet, base_name='user_survey_agent')
router.register(r'rentResult', views.RentResultViewSet, base_name='survey-result')
router.register(r'tenants', views.TenantViewSet, base_name='tenants-update')

app_name = 'survey'
urlpatterns = [
    url(r'^rent/$', views.RentingSurveyTemplate.as_view(), name="rentingSurvey"),
    url(r'^rent/(?P<survey_url>.*)/$', views.RentingResultTemplate.as_view(), name="rentSurveyResult"),

    # Api
    url(r'^api/', include(router.urls))
]

cocoon/userAuth/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'resendVerificationEmail', views.ResendVerificationEmail, base_name='userAuth-resend-verification')
router.register(r'agentClients', views.RetrieveClientsViewSet, base_name='userAuth-retrieve-clients')

app_name = 'userAuth'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginPage, name='loginPage'),
    # url(r'^register/$', views.SignUpView.as_view(), name='signup'),
    url(r'^register/hunter/', views.ApartmentHunterSignupView.as_view(), name='hunter_signup'),
    url(r'^register/broker/', views.BrokerSignupView.as_view(), name='broker_signup'),
    url(r'^password_change/$', views.change_password, name='change_password'),
    url(r'^logout/$', views.logoutPage, name='logoutPage'),
    url(r'^profile$', views.user_profile, name='user_profile'),
    url(r'^tourSetup/$', views.TourSetup.as_view(), name='tour_setup'),
    url(r'^myClients/$', views.MyClients.as_view(), name='my_clients'),

    # Email verification
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_account, name='activateAccount'),
    url(r'^termsofuse', views.TermsOfUse.as_view(), name='terms_of_use'),

    # Api
    url(r'^api/', include(router.urls))
]

config/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^adminBostoncocoon/', admin.site.urls),
    url(r'^', include('cocoon.homePage.urls')),
    url(r'^userAuth/', include('cocoon.userAuth.urls')),
    url(r'^houseDatabase/', include('cocoon.houseDatabase.urls')),
    url(r'^commutes/', include('cocoon.commutes.urls')),
    url(r'^survey/', include('cocoon.survey.urls')),
    url(r'^scheduler/', include('cocoon.scheduler.urls')),
    url(r'^signatures/', include('cocoon.signature.urls')),
    url(r'^password_reset/$', auth_views.password_reset,
        {
            'post_reset_redirect': reverse_lazy('password_reset_done'),
            'html_email_template_name': 'registration/password_reset_html_email.html'
        },
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cocoon.views.error_404_view'

cocoon/survey/views.py
# Import Django modules
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Import Survey algorithm modules
from .cocoon_algorithm.rent_algorithm import RentAlgorithm
from .models import RentingSurveyModel
from .forms import RentSurveyForm, RentSurveyFormEdit, TenantFormSet, TenantFormSetJustNames
from .survey_helpers.save_polygons import save_polygons
from .serializers import HomeScoreSerializer, RentSurveySerializer, SurveySubscribeSerializer
from .constants import NUMBER_OF_HOMES_RETURNED

# Cocoon Modules
from cocoon.userAuth.forms import ApartmentHunterSignupForm
from cocoon.userAuth.models import UserProfile, MyUser
from cocoon.houseDatabase.models import RentDatabaseModel
from cocoon.userAuth.forms import LoginUserForm

# Rest Framework
from rest_framework import viewsets, mixins
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from .tasks import compute_survey_result_iteration_task

# Load the logger
import logging
logger = logging.getLogger(__name__)


class RentingSurveyTemplate(TemplateView):
    """
    Template to load the react for the rent survey page
    """

    template_name = "survey/rentForm.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['component'] = RentingSurveyTemplate.__name__
        return data


@method_decorator(login_required, name='dispatch')
class RentingResultTemplate(DetailView):
    """
    Detail view to load the react for the rent result page

    The reason why the detail view is used is to cause a 404 if the user
        tries to load a survey that doesn't exist or they don't own
    """

    template_name = "survey/rentResult.html"
    model = RentingSurveyModel
    slug_field = 'url'
    slug_url_kwarg = 'survey_url'

    def get_queryset(self):
        """
        The survey must be associated with the currently logged in user
        """
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        return retrieve_survey_queryset(user_profile)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['component'] = RentingResultTemplate.__name__
        return data


class RentSurveyAgentViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):

    serializer_class = RentSurveySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        if user_profile.user.is_broker:
            return retrieve_survey_queryset(user_profile)
        else:
            raise 404

    def retrieve(self, request, *args, **kwargs):
        """
        Retrieves a survey based on either the id or the survey url
        :param request:
        :param args:
        :param kwargs:
            type: 'by_url' -> The survey is retrieved by using the survey url
                   other -> Anything else will default the request to retrieve the survey via id
            data_type: 'survey_subscribe' -> Returns the data just for the survey subscribe data
                        other -> Returns the Survey Serialized data
            pk: Stores either the survey url or the survey depending on the type
        :return: A serialized response with the survey that was retrieved
        """
        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Determine the method for getting the survey
        retrieve_type = self.request.query_params.get('type', None)
        data_type = self.request.query_params.get('data_type', None)

        # Retrieve the survey id/url
        pk = kwargs.pop('pk', None)

        client = get_object_or_404(MyUser, id=pk)

        surveys = RentingSurveyModel.objects.filter(user_profile=client.userProfile)

        serializer = RentSurveySerializer(surveys, context={'user': user_profile.user}, many=True)
        return Response(serializer.data)


class RentSurveyViewSet(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, mixins.ListModelMixin,
                        mixins.CreateModelMixin, viewsets.GenericViewSet):

    serializer_class = RentSurveySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_permissions(self):
        """
        Dynamically get permissions because we only allow the user to not be authenticated on the
            create method
        """
        if self.action == 'create':
            permission_classes = [AllowAny]
        else:
            permission_classes = [IsAuthenticated]

        return [permission() for permission in permission_classes]

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        return retrieve_survey_queryset(user_profile)

    def list(self, request, *args, **kwargs):
        """
        When the surveys are being listed, only return the surveys that belong to the user.
        This is needed because the queryset if the user is an admin now includes all surveys,
            therefore when the list api is requested, just returns that users surveys
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        qs = RentingSurveyModel.objects.filter(user_profile=user_profile)
        serializer = RentSurveySerializer(qs, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        """
        Retrieves a survey based on either the id or the survey url
        :param request:
        :param args:
        :param kwargs:
            type: 'by_url' -> The survey is retrieved by using the survey url
                   other -> Anything else will default the request to retrieve the survey via id
            data_type: 'survey_subscribe' -> Returns the data just for the survey subscribe data
                        other -> Returns the Survey Serialized data
            pk: Stores either the survey url or the survey depending on the type
        :return: A serialized response with the survey that was retrieved
        """
        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Determine the method for getting the survey
        retrieve_type = self.request.query_params.get('type', None)
        data_type = self.request.query_params.get('data_type', None)

        # Retrieve the survey id/url
        pk = kwargs.pop('pk', None)

        if retrieve_type == 'by_url':
            # Retrieve the associated survey with the request
            survey = retrieve_survey(user_profile, url=pk)
        else:
            survey = retrieve_survey(user_profile, pk=pk)

        if data_type == 'survey_subscribe':
            serializer = SurveySubscribeSerializer(survey)
            return Response(serializer.data)
        else:
            serializer = RentSurveySerializer(survey, context={'user': user_profile.user})
            return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        """
        Retrieves all the data from the frontend
        Then the data is parsed to each of the sections
        If all the forms are valid, they are saved and the redirect url is returned
        Otherwise the form errors are returned
        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        data = self.request.data['data']

        # Parse data to correct format
        survey_data = None
        tenant_data = None
        user_data = None

        # Save data if it exists
        if 'generalInfo' in data:
            survey_data = data['generalInfo']
        if 'amenitiesInfo' in data:
            survey_data.update(data['amenitiesInfo'])
        if 'tenantInfo' in data:
            tenant_data = data['tenantInfo']
        if 'detailsInfo' in data:
            user_data = data['detailsInfo']

        form = RentSurveyForm(survey_data)
        tenants = TenantFormSet(tenant_data)
        user_form = None

        user = self.request.user
        if user.is_anonymous():
            user = None
        user_signing_in = False

        # Determines if the user is trying to sign in or create a new account and creates
        #   the corresponding form
        if not self.request.user.is_authenticated():
            if user_data.get('user_logging_in', False):
                user_signing_in = True
                user_form_data = {
                    'username': user_data.get('email'),
                    'password': user_data.get('password1'),
                }
                user_form = LoginUserForm(request, user_form_data)
            else:
                user_form = ApartmentHunterSignupForm(user_data)

        # Determines if any of the forms is not valid, and only check user_form if it exists
        forms_valid = form.is_valid() and tenants.is_valid() and user_form.is_valid() if user_form is not None else True

        # Only bother checking if all the forms are valid and there is a user_form
        # Called after checking to see if all the forms are valid
        if forms_valid and user_form is not None:

cocoon/userAuth/templates/userAuth/change_password.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Change Password{% endblock %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'userAuth/css/change_password.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
{% endblock %}


{% block content %}
    <div class="row form-gap">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="text-center">
                        <h3><i class="fa fa-lock fa-4x"></i></h3>
                        <div class="panel-body" align="left">
                            <h3>Change password</h3>
                            <form method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Change password</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cocoon/userAuth/templates/userAuth/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cocoon | Login {% endblock title %}

{% block head %}
{{ block.super }}

    <!-- Login Styling -->
    <link href="{% static "userAuth/signin.css" %}" rel="stylesheet">
    <link href="{% static "userAuth/general_auth.css" %}" rel="stylesheet">
{% endblock head %}

{% comment %}
Leaving empty nav_bar block to prevent the nav bar from showing up
{% endcomment %}
{% block nav_bar %} {% endblock nav_bar %}

{% block content %}

    <div class="row">
        <div class="col-sm-2 col-sm-offset-2 header">
            <img class="logo" src="{% static 'homePage/cocoon_logo.png' %}">
        </div>
    <div class="col-sm-4">
        <p class="welcome_text">Welcome to Cocoon</p>
    </div>

    </div>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form class="form-signin form-horizontal" action="{% url 'userAuth:loginPage' %}" method='POST'>
        {% csrf_token %}
        <div class="form-group">
            {% if error_message %}
                <div class="row">
                    <div style="color:red">
                        <p><strong>
                            {% for error in error_message %}
                                {{ error }}
                            {% endfor %}
                        </strong></p>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            <h2 class="form-signin-heading">Please sign in:</h2>
        </div>
        <div class="form-group">
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            {{ form.password }}
            {{ form.password.errors }}
            <div class="checkbox">
                <label>
                    {{ form.remember.errors }}
                    {{ form.remember }} Remember Me
                </label>
            </div>
        </div>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <div class="form-group">
            <button class="btn btn-lg btn-primary btn-block" value="login" type="submit">Sign in</button>
        </div>
    </form>
    <p style="text-align:center">
	    <a href="{% url 'userAuth:hunter_signup' %}">Register New User</a>
	</p>
    <p style="text-align:center">
        <a href="{% url 'password_reset' %}">Forgot Password</a>
    </p>
       <p style="text-align:center">
	    <a href="{% url 'homePage:index' %}">Return to the Home Page</a>
	</p>

{% endblock content %}

{% block endScripts %}

    {{ block.super }}
{% endblock %}

cocoon/userAuth/templates/userAuth/my_clients.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | My Clients{% endblock %}

{% block container_type %}
{% endblock %}

{% block content %}
    <div id="reactWrapper"></div>
{% endblock %}

{% block endScripts %}
    {{ block.super }}
    <script src="{% static 'cocoon/main/ajax/getCookie.js' %}"></script>
    {% include 'frontend/react_base.html' %}
    <script src="{% static 'frontend/js/userAuth.bundle.js' %}"></script>
{% endblock %}

cocoon/userAuth/templates/userAuth/register.html
{% extends "bootstrapJQuery.html" %}
{% load static %}
{% block title %}Register{% endblock title %}

{% block head %}
    {{ block.super }}
    <!-- Register page stylesheet-->
    <link href="{% static "userAuth/register.css" %}" rel="stylesheet">
    <link href="{% static "userAuth/general_auth.css" %}" rel="stylesheet">
{% endblock head %}

{% comment %}
Leaving empty nav_bar block to prevent the nav bar from showing up
{% endcomment %}
{% block nav_bar %}{% endblock nav_bar %}

{% block content %}

        <div class="row">
        <div class="col-sm-2 col-sm-offset-2 header">
            <img class="logo" src="{% static 'homePage/cocoon_logo.png' %}">
        </div>
    <div class="col-sm-4">
        <p class="welcome_text">Welcome to Cocoon</p>
    </div>

    </div>

    <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post" class="form-register form-horizontal">
                <div class="form-group">
                    <h2 class="form-register-heading">Create an Account!</h2>
                </div>
                <div class="form-group">
                    {% if error_message %}
                        <div class="row">
                            <div style="color:red">
                                <p><strong>
                                    {% for error in error_message %}
                                        {{ error }}
                                    {% endfor %}
                                </strong></p>
                            </div>
                        </div>
                    {% endif %}
                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <button class="btn btn-large btn-primary btn-block" value="Register" type="submit">Register!</button>
                </div>
            </form>
        </div>
    </div>
    <p style="text-align:center">
        <a href="{% url 'userAuth:loginPage' %}">Return to Login Page</a>
    </p>
    </p>
       <p style="text-align:center">
	    <a href="{% url 'homePage:index' %}">Return to the Home Page</a>
	</p>
{% endblock content %}

cocoon/userAuth/templates/userAuth/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Register{% endblock title %}

{% block content %}
  <h2>Sign up for a free account</h2>
  <p class="lead">Select below the type of account you want to create</p>
  <a href="{% url 'userAuth:broker_signup' %}" class="btn btn-student btn-lg" role="button">I'm a broker</a>
  <a href="{% url 'userAuth:hunter_signup' %}" class="btn btn-teacher btn-lg" role="button">I'm looking for an apartment</a>
{% endblock %}

cocoon/userAuth/templates/userAuth/signup_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Register{% endblock title %}

{% block head %}
    {{ block.super }}
    <!-- Register page stylesheet-->
    <link href="{% static "userAuth/register.css" %}" rel="stylesheet">
    <link href="{% static "userAuth/general_auth.css" %}" rel="stylesheet">
{% endblock head %}

{% comment %}
Leaving empty nav_bar block to prevent the nav bar from showing up
{% endcomment %}
{% block nav_bar %}{% endblock nav_bar %}

{% block content %}

        <div class="row">
        <div class="col-sm-2 col-sm-offset-2 header">
            <img class="logo" src="{% static 'homePage/cocoon_logo.png' %}">
        </div>
    <div class="col-sm-4">
        <p class="welcome_text">Welcome to Cocoon</p>
    </div>

    </div>

    <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <form method="post" class="form-register form-horizontal">
                <div class="form-group">
                    <h2 class="form-register-heading">Create an Account!</h2>
                </div>
                <div class="form-group">
                    {% if error_message %}
                        <div class="row">
                            <div style="color:red">
                                <p><strong>
                                    {% for error in error_message %}
                                        {{ error }}
                                    {% endfor %}
                                </strong></p>
                            </div>
                        </div>
                    {% endif %}
                </div>
                {% csrf_token %}
                {{ form.as_p }}
            <br>
                <p>By registering for an account you accept our <a href="{% url 'userAuth:terms_of_use' %}">terms and conditions</a></p>
            <br>
                <div class="form-group">
                    <button class="btn btn-large btn-primary btn-block" value="Register" type="submit">Register!</button>
                </div>
            </form>
        </div>
    </div>
    <p style="text-align:center">
        <a href="{% url 'userAuth:loginPage' %}">Return to Login Page</a>
    </p>
    </p>
       <p style="text-align:center">
	    <a href="{% url 'homePage:index' %}">Return to the Home Page</a>
	</p>
{% endblock content %}

cocoon/userAuth/templates/userAuth/surveys.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Tour Setup{% endblock %}

{% block container_type %}
{% endblock %}

{% block content %}
    <div id="reactWrapper"></div>
{% endblock %}

{% block endScripts %}
    {{ block.super }}
    <script src="{% static 'cocoon/main/ajax/getCookie.js' %}"></script>
    {% include 'frontend/react_base.html' %}
    <script src="{% static 'frontend/js/userAuth.bundle.js' %}"></script>
{% endblock %}

cocoon/userAuth/templates/userAuth/terms_and_conditions.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Terms & Conditions{% endblock %}

{% block content %}
    <h3>My very long terms and conditions.</h3>
{% endblock %}

cocoon/userAuth/templates/userAuth/tour_setup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | Tour Setup{% endblock %}

{% block container_type %}
{% endblock %}

{% block content %}
    <div id="reactWrapper"></div>
{% endblock %}

{% block endScripts %}
    {{ block.super }}
    <script src="{% static 'cocoon/main/ajax/getCookie.js' %}"></script>
    {% include 'frontend/react_base.html' %}
    <script src="{% static 'frontend/js/userAuth.bundle.js' %}"></script>
{% endblock %}

cocoon/userAuth/templates/userAuth/user_groups.html
{% extends "bootstrapJQuery.html" %}
{% load static %}
{% block title %}Unicorn{% endblock %}
{% block head %}
    {{ block.super }}
    <!-- JQuery UI style sheet, mostly used for slider ui -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'survey/rentingSurvey.css' %}">
{% endblock %}

{% block nav-survey %}<li class="active"><a>Survey</a></li>{% endblock %}

{% block content %}
    <div id="reactWrapper"></div>
{% endblock %}


{% block endScripts %}
    <script src="{% static 'cocoon/main/ajax/getCookie.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.js' %}"></script>
    <script src="{% static 'cocoon/main/js/navbar.js' %}"></script>
    {% include 'frontend/react_base.html' %}
    <script src="{% static 'frontend/js/userAuth.bundle.js' %}"></script>
{% endblock %}

{% block footer %}



    <footer class="footer">
        Copyright Cocoon 2018. All rights reserved.
    </footer>

{% endblock %}

cocoon/userAuth/templates/userAuth/user_profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cocoon | User Profile{% endblock %}


{% block head %}
    {{ block.super }}
    <!-- Custom StyleSheets -->
    <link rel="stylesheet" href="{% static 'userAuth/css/user_profile.css' %}">
{% endblock %}


{% block content %}

    {% comment %}
        Displays any error messages associated with the form
    {% endcomment %}
    <div class="row">
        <div class="col-sm-12">
            {% if error_message %}
                <div class="row">
                    <div class="col-sm-offset-3 col-sm-6" style="color:red">
                        <p><strong>{{ error_message }}</strong></p>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>

    {% comment %}
        This block contains the picture and button associated with the profile
    {% endcomment %}
    <div class="row">
        <div class="col-lg-12 col-sm-12">
            <div class="card hovercard">
                <div class="card-background">
                    <img class="card-bkimg" alt="" src="{% static 'userAuth/cityBackground.jpg' %}">
                </div>
                <div class="useravatar">
                    <img alt="" src="{% static 'userAuth/unicornProfilePic.jpeg' %}">
                </div>
                <div class="card-info"><span class="card-title">{{ userProfile.user.get_full_name }}</span>
                </div>
            </div>
            <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
                <div class="btn-group" role="group">
                    <button type="button" id="stars"
                            class="btn btn-primary"
                            href="#tab1" data-toggle="tab"><span
                            class="glyphicon glyphicon-user" aria-hidden="true"></span>
                        <div class="hidden-xs">Profile</div>
                    </button>
                </div>
            </div>

            {% comment %}
                This part contains the data associated with the user profile.
            {% endcomment %}
            <div class="well">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tab1">
                        <div class="row">
                            <h3 class="col-sm-12">Account Setting</h3>
                            <div class="col-sm-9 col-sm-offset-3">
                                <form class="form-horizontal" action="{% url 'userAuth:user_profile' %}"
                                      method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        {{ form.as_p }}
                                    </div>
                                    <p>Number of Rent Surveys: {{ numRentSurveys }}</p>
                                    <p>Account type: </p>
                                    <ul style="list-style-type:none">
                                        <li>{% if userProfile.user.is_broker %} Broker {% endif %}</li>
                                        <li>{% if userProfile.user.is_hunter %} Hunter {% endif %}</li>
                                    </ul>
                                    {% if userProfile.referred_agent %}
                                        <p> Referred by agent:</p>
                                        <ul style="list-style-type:none">
                                            <li>{{ userProfile.referred_agent }}</li>
                                        </ul>
                                    {% endif %}
                                    {% if userProfile.user.is_broker %}
                                        <p>User Url: {{ userProfile.url }}</p>
                                    {% endif %}
                                    <div class="form-group">
                                        <button type="submit" id="Submit" class="btn btn-primary">Save Changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <p style="text-align:center">
                <a href="{% url 'userAuth:change_password' %}">Reset your Password</a>
            </p>
        </div>
    </div>
{% endblock %}