cocoon/homePage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homePage'
urlpatterns = [
    url(r'^$', views.LandingPage.as_view(), name='index'),
]

cocoon/survey/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'rentSurvey', views.RentSurveyViewSet, base_name='user_survey')
router.register(r'rentSurveyAgent', views.RentSurveyAgentViewSet, base_name='user_survey_agent')
router.register(r'rentResult', views.RentResultViewSet, base_name='survey-result')
router.register(r'tenants', views.TenantViewSet, base_name='tenants-update')

app_name = 'survey'
urlpatterns = [
    url(r'^rent/$', views.RentingSurveyTemplate.as_view(), name="rentingSurvey"),
    url(r'^rent/(?P<survey_url>.*)/$', views.RentingResultTemplate.as_view(), name="rentSurveyResult"),

    # Api
    url(r'^api/', include(router.urls))
]

config/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^adminBostoncocoon/', admin.site.urls),
    url(r'^', include('cocoon.homePage.urls')),
    url(r'^userAuth/', include('cocoon.userAuth.urls')),
    url(r'^houseDatabase/', include('cocoon.houseDatabase.urls')),
    url(r'^commutes/', include('cocoon.commutes.urls')),
    url(r'^survey/', include('cocoon.survey.urls')),
    url(r'^scheduler/', include('cocoon.scheduler.urls')),
    url(r'^signatures/', include('cocoon.signature.urls')),
    url(r'^password_reset/$', auth_views.password_reset,
        {
            'post_reset_redirect': reverse_lazy('password_reset_done'),
            'html_email_template_name': 'registration/password_reset_html_email.html'
        },
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cocoon.views.error_404_view'

cocoon/homePage/forms.py
from django import forms


class SurveyType(forms.Form):
    SURVEY_TYPES = [
        ('rent', 'Rent'),
       # ('buy', 'Buy'),
    ]
    survey_type = forms.ChoiceField(
        choices=SURVEY_TYPES,
        widget=forms.RadioSelect()
    )

cocoon/homePage/views.py
# Django Modules
from django.views.generic import TemplateView


class LandingPage(TemplateView):

    template_name = "homePage/landingPage.html"


class AboutUs(TemplateView):

    template_name = "homePage/aboutUs.html"

cocoon/homePage/templates/homePage/aboutUs.html
{% extends "base.html" %}
{% load static %}
{% block title %}Contact{% endblock %}

{% block head %}
{{ block.super }}

    <link href="{% static 'homePage/about_us.css' %}" rel="stylesheet">

{% endblock %}

{% block container_type %}container{% endblock %}
{% block content %}
    <div class="jumbotron" style="width: 80%; margin: 5% auto; text-align: center">
        <h1>About Us</h1>
    </div>
    </p>
    <h1 class="Mission" style="text-align: center"><span style="font-size: 24px;">Mission Statement</span></h1>
    <p><span style="font-size: 16px">
    Cocoon exists to redefine the apartment-finding process. We strive to raise the bar on quality of service, while simplifying every step of the way to be easier, quicker, and substantially less expensive.
We achieve this by listening to our clients, working hard, always being open to criticism, thinking critically, researching thoroughly, testing everything, and innovating radically. We use radically new technology to break the glass ceiling that has defined real estate for years.

	Finding a new apartment is a big process. We help our tenants feel confident that they have found the best possible place to live.
</span></p>
    <p><span style="font-size: 16px;"><strong><br></strong></span></p>

    <h1 style="text-align: center;"><span style="font-size: 24px;">Why We Started</span></h1>
    <p><span style="font-size: large;">	The present market is swamped with both limited-utility, expensive brokerages,  and with confusing, overwhelming technology companies that overload people with mostly unuseful information. Finding a place to live takes as long as before the internet, and nobody in real estate seems to care. Brokerages and tech companies alike profit hugely from poor service, and clients have no options for radically better service.

	We wanted to drop a bomb on the industry by doing the unheard of: top-tier service in far less time and for far less money.
</span></p>
    <p><span style="font-size: large;"><br></span></p>

    <h1 style="text-align: center;"><span style="font-size: 24px;">Who We Are</span></h1>
    <p><span style="font-size: 16px;">
        We are currently College Students who have struggled in the past with the real estate market in Boston. On top
            of our school assignments, we are working diligently to continue this project forward. We are ecstatic that you
            are visiting our website and hope that you find it an enjoyable and helpful experience!!
    </span></p>
    <p><span style="font-size: large;"><br></span></p>

    <div class="the-team">
    <h1><span>The Team</span></h1>
    <p><span class="team-member">Tomás Jurgensen</span></p>
    <p class="description">Cocoon’s CEO co-founder, Tomás was born in Boston and raised in Arlington to a Brazilian mother and Danish-American father from MIT. Tomás went to the Belmont Hill School and recently graduated from Bates College with a mathematics major, Russian minor, and a concentration in Psychology and Philosophy. In his free time, Tomás practices Brazilian Jiu-Jitsu and enjoys travelling, painting, and playing piano. At Cocoon, Tomás oversees all non-technical matters.
</p>
    <p><span class="team-member">Alex Agudelo</span></p>
    <p class="description">Cocoon’s CTO and co-founder, Alex was also born in Boston and raised in Arlington. He attended B.C. High and is currently a senior at Northeastern University. He majors in Electrical and Computer Engineering, and has experience working at MIT Lincoln Labs and currently at Doble Engineering. In his free time, he runs and competes in triathlons. At Cocoon, Alex handles all technical matters, including algorithm engineering, full stack platform development, web security, SEO, and database engineering.
</p>
    <p><span class="team-member">Sean Rayment</span></p>
    <p clas="description">
	Cocoon’s head developer, Sean is from Medfield MA, also studied at the Belmont Hill School, and currently studies at Brown University, where he double majors in Mathematics and Computer Sciences. For fun, he likes to read and writes Dungeons and Dragons campaigns.
At Cocoon, Sean handles front-end web development including designing our platform’s user interface and experience; he also does all graphic design.
</p>
        </div>

    <h1 style="text-align: center;"><span style="font-size: 24px;">Our Solution</span></h1>
    <p><span style="font-size: 16px;">
        We developed an intricate algorithm to allow you to indicate your desires and we will then match you with the
            home that best meets you needs. The survey will take a few minutes to fill out and in seconds a large list of
            homes ranked from the best match to less ideal matches will be displayed. Homes will be filtered on commute time,
            number of bedrooms, cost, move in time, etc. The survey allows for more or less customizations depending on
            how refined you want the search to be. You can add homes to your favorite list if you want to revisit them later.
            When you the home you want to visit, select the home and the options for contacting the agent will be shown!
            It is that easy!
    </span></p>
    <p><span style="font-size: 16px;"><br></span></p>

    <h1 style="text-align: center;"><span style="font-size: 24px;">What You Can Do</span></h1>
    <p><span style="font-size: 16px;">
        Please reach out to us if you have any questions or concerns! We strive to best fit your needs and hope that you
            can help us improve! The real estate market is a daunting place and we strive to make the transition to your
            best ideal home that much easier!
    </span></p>
    <br>

{% endblock %}

cocoon/homePage/templates/homePage/landingPage.html
{% extends 'base.html' %}
{% load static %}
{% load intercom %}

{% block head %}
    {{ block.super }}
  {% comment %} Domain Verfication{% endcomment %}
  <meta name="google-site-verification" content="EZpbJ3VrkWORskv6xVg5hoxs3cjmN7UBjbKu6AZW4C8"/>
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cocoon | Find yours with us.</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'homePage/cocoon_logo.png' %}"/>
  <link href="{% static 'homePage/newLandingPage.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'homePage/aos-scroll-reveal.css' %}" />
  <link rel="stylesheet" href="{% static 'homePage/tiny-slider.css' %}">
{% endblock %}

{% block container_type %}{% endblock %}

{% block content %}

    <!-- SLIDER START -->
      <section id="onboarding">
        <span id="close-slider" class="toggle-slider">x</span>
        <div class="container">

          <div class="my-slider">
            <div class="slide">
              <div class="image-wrapper">
                <img src="{% static 'homePage/survey-shot.png' %}" alt="">
              </div>
              <h2>1) Complete our smart survey detailing your every need!</h2>
                <p>Take our smart survey to tell our computers what you need and what you want. This allows our
                    first-in-class algorithms to curate the best apartments for you on-market, like a robot wine
                    sommelier for apartments. We only use the finest databases, and all our listings are landlord- or
                    broker-validated, so you never have to worry about bait-and-switches or scam listings.</p>
                    <p>The computer assigns a score (0-100) for each viable property according to how ideal the
                        property is for you. The higher the score, the better-matched our computers think that property
                        is for you.</p>
                    <p>Sometimes your survey will return very few, no, or poorly rated properties. In this case, don’t
                        worry! Because Cocoon automatically pulls the best and freshest validated data available
                        anywhere, this just means that there truly isn’t anything trustworthy on-market.
                        If you’re in a pinch to move, this means you should relax some constraints to help increase
                        the pool of viable properties; otherwise, if you’re searching with more time, we recommend
                        signing up for our auto-compute feature, where the computer will study the market and notify
                        you when a well-matched property becomes available.</p>
              <a href="{% url 'survey:rentingSurvey' %}">Get Started</a>
            </div>

            <div class="slide">
              <div class="image-wrapper">
                <img src="{% static 'homePage/results-shot.png' %}" alt="">
              </div>
              <h2>2) See your favorites with an expert tour guide.</h2>
                <p>Once you’re ready to see some properties in person (or over a video call), we automatically
                    calculate the best route for the properties you’ve chosen, schedule the tour for you on a day
                    and time that’s convenient for you, and ready an expert licensed affiliated real estate agent to
                    be your personal tour guide.
                </p>
                <p>If you’re out of town and still want to tour, our tour guides can also accommodate remote video
                    touring via FaceTime or Skype- just let them know your preference when they reach out to you on
                    their introductory call a few days before your tour.
                </p>
                <p>The tour itself will be of the properties you chose to visit- sometimes one or more of these gets
                    rented out quickly before you get a chance to tour them. In this case, our tour guides will set
                    up backup properties for you to see to make sure you get a good, thorough tour.
                </p>
                <p>Once you go on the tour, hopefully you’re ready to apply on a property! At this point we’ll reach
                    out to you to work with you on understanding the process and paperwork to lock in your property.
                </p>
              <a href="{% url 'survey:rentingSurvey' %}">Get Started</a>
            </div>

            <div class="slide">
              <div class="image-wrapper">
                <img src="{% static 'homePage/schedule-shot.png' %}" alt="">
              </div>
              <h2>3) Found the one? We’ll help you get it quickly and painlessly!</h2>
                <p>We're so much more than Zillow or Compass; once you've decided on your dream place, Cocoon makes it
                    super easy for you to apply and win your apartment by making several vital steps available to you
                    instantly via our on-demand digital platform: from instantly digitized paperwork to on-demand live
                    customer service, we make sure that every step of your apartment-getting journey is as simple and
                    stress free as possible.
                </p>
                <p>Traditionally, the transference of money in a rental transaction (nevermind the paperwork) is
                    complicated and confusing. Cocoon is a fully insured and licensed brokerage, so we can help you
                    make this easy with 24/7 advisors, digital paperwork, and many more cool features coming soon!
                </p>
              <a href="{% url 'survey:rentingSurvey' %}">Get Started</a>
            </div>
          </div>

            <div class="slider-controls">
                <span class="slider-text" id="slider-prev">Prev</span>
                <div class="circle-controls">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <span class="slider-text" id="slider-next">Next</span>
            </div>

        </div>
      </section>
      <!-- SLIDER END -->

      <div id="landing-page-body">
        <section id="hero">
          <div class="container">
            <div class="hero-text">
              <h1>Less is <span class="redOrange">more</span>.
                  <br>We'll find you the best</h1>
              <p>Cocoon pairs our cutting edge software with clever new best practices to find your next home. Join our
                open beta and find yours with us.</p>
              <div class="hero-buttons">
                <a href="{% url 'survey:rentingSurvey' %}">Start Survey</a>
                <span class="toggle-video">Watch a Demo <i class="material-icons">play_circle_outline</i></span>
              </div>
            </div>
            <div class="hero-img">
              <img src="{% static 'homePage/isometric-homes_red.png' %}" alt="">
            </div>
          </div>
        </section>

        <section id="steps">
          <div class="container">
            <h2>Here's how we make your <b>life better</b>:</h2>
          </div>
          <div class="steps-wrapper">
            <div class="img-wrapper">
              <img src="{% static 'homePage/room-with-dog.jpg' %}" alt="">
            </div>
            <div class="how-to-wrapper">

              <div data-aos="zoom-in-left" class="step-box">
                <div class="icon">
                  <img src="{% static 'homePage/screen.svg' %}" alt="">
                </div>
                <div class="step-text">
                  <h2>No More Digging</h2>
                  <p>Instead of burying you with irrelevant listings like all those old-school sites,
                      Cocoon finds the perfect rentals for you by analyzing every apartment on-market with
                      our powerful tech, only showing you your best personalized matches.</p>
                  <span id="learn-1" class="step-learn-more">Learn More <i class="material-icons">keyboard_arrow_right</i></span>
                </div>
              </div>

              <div data-aos="zoom-in-left" class="step-box">
                <div class="icon">
                  <img src="{% static 'homePage/houses.svg' %}" alt="">
                </div>
                <div class="step-text">
              <h2>Free Tours, Painfree Process</h2>
                  <p>Once Cocoon's helped you assemble your ideal tour list (it might take a few visits!),
                      our platform makes it easy for you to both schedule and see them in person or on
                      Facetime with our licensed tour guides.</p>
                  <span id="learn-2" class="step-learn-more">Learn More <i class="material-icons">keyboard_arrow_right</i></span>
                </div>
              </div>

              <div data-aos="zoom-in-left" class="step-box">
                <div class="icon">
                  <img src="{% static 'homePage/home.svg' %}" alt="">
                </div>
                <div class="step-text">
                  <h2>Peeps when you need us</h2>
                  <p>Robot Realtor. Apartment Sommelier. However you describe Cocoon, you can relax knowing we have
                      awesome real estate experts and generally cool people available 24/7 to make sure you get the
                      best apartment possible.  Once you make an account you will see a chat button on the bottom right.
                      We would love for you to say hi and/or ask about any questions you might have!</p>
                  <span id="learn-3" class="step-learn-more">Learn More <i class="material-icons">keyboard_arrow_right</i></span>
                </div>
              </div>

            </div>
          </div>
        </section>

        <section id="banner">
          <div class="container">
{#            <h3 class="red">Put our first-in-class tech to work helping you work less on apartment hunting</h3>#}
            <h2>Cocoon exists to save you the stress and energy of finding - and getting - your dream apartment. So kick
              back your feet, fire up your laptop, and find yours with us. </h2>
          </div>
        </section>
      </div>

    <div class="video-wrapper" style="display: none;">
        <div class="video-container">
            <div class="close-video">
                <i class="material-icons">close</i>
            </div>
            <div class='embed-container'><iframe src='https://www.youtube.com/embed/IC8MJXVoT_g' frameborder='0' allowfullscreen></iframe></div>
        </div>
    </div>

{% endblock %}

{% intercom_tag %}
{% block endScripts %}
    {{ block.super }}
    <script src="{% static 'homePage/aos-scroll-reveal.js' %}"></script>
    <script src="{% static 'homePage/tiny-slider.js' %}"></script>
    <script src="{% static 'homePage/landingPage.js' %}"></script>
{% endblock %}