cocoon/survey/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'rentSurvey', views.RentSurveyViewSet, base_name='user_survey')
router.register(r'rentSurveyAgent', views.RentSurveyAgentViewSet, base_name='user_survey_agent')
router.register(r'rentResult', views.RentResultViewSet, base_name='survey-result')
router.register(r'tenants', views.TenantViewSet, base_name='tenants-update')

app_name = 'survey'
urlpatterns = [
    url(r'^rent/$', views.RentingSurveyTemplate.as_view(), name="rentingSurvey"),
    url(r'^rent/(?P<survey_url>.*)/$', views.RentingResultTemplate.as_view(), name="rentSurveyResult"),

    # Api
    url(r'^api/', include(router.urls))
]

config/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^adminBostoncocoon/', admin.site.urls),
    url(r'^', include('cocoon.homePage.urls')),
    url(r'^userAuth/', include('cocoon.userAuth.urls')),
    url(r'^houseDatabase/', include('cocoon.houseDatabase.urls')),
    url(r'^commutes/', include('cocoon.commutes.urls')),
    url(r'^survey/', include('cocoon.survey.urls')),
    url(r'^scheduler/', include('cocoon.scheduler.urls')),
    url(r'^signatures/', include('cocoon.signature.urls')),
    url(r'^password_reset/$', auth_views.password_reset,
        {
            'post_reset_redirect': reverse_lazy('password_reset_done'),
            'html_email_template_name': 'registration/password_reset_html_email.html'
        },
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cocoon.views.error_404_view'

cocoon/survey/views.py
# Import Django modules
from django.shortcuts import get_object_or_404
from django.db import transaction
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Import Survey algorithm modules
from .cocoon_algorithm.rent_algorithm import RentAlgorithm
from .models import RentingSurveyModel
from .forms import RentSurveyForm, RentSurveyFormEdit, TenantFormSet, TenantFormSetJustNames
from .survey_helpers.save_polygons import save_polygons
from .serializers import HomeScoreSerializer, RentSurveySerializer, SurveySubscribeSerializer
from .constants import NUMBER_OF_HOMES_RETURNED

# Cocoon Modules
from cocoon.userAuth.forms import ApartmentHunterSignupForm
from cocoon.userAuth.models import UserProfile, MyUser
from cocoon.houseDatabase.models import RentDatabaseModel
from cocoon.userAuth.forms import LoginUserForm

# Rest Framework
from rest_framework import viewsets, mixins
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from .tasks import compute_survey_result_iteration_task

# Load the logger
import logging
logger = logging.getLogger(__name__)


class RentingSurveyTemplate(TemplateView):
    """
    Template to load the react for the rent survey page
    """

    template_name = "survey/rentForm.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['component'] = RentingSurveyTemplate.__name__
        return data


@method_decorator(login_required, name='dispatch')
class RentingResultTemplate(DetailView):
    """
    Detail view to load the react for the rent result page

    The reason why the detail view is used is to cause a 404 if the user
        tries to load a survey that doesn't exist or they don't own
    """

    template_name = "survey/rentResult.html"
    model = RentingSurveyModel
    slug_field = 'url'
    slug_url_kwarg = 'survey_url'

    def get_queryset(self):
        """
        The survey must be associated with the currently logged in user
        """
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        return retrieve_survey_queryset(user_profile)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['component'] = RentingResultTemplate.__name__
        return data


class RentSurveyAgentViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):

    serializer_class = RentSurveySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        if user_profile.user.is_broker:
            return retrieve_survey_queryset(user_profile)
        else:
            raise 404

    def retrieve(self, request, *args, **kwargs):
        """
        Retrieves a survey based on either the id or the survey url
        :param request:
        :param args:
        :param kwargs:
            type: 'by_url' -> The survey is retrieved by using the survey url
                   other -> Anything else will default the request to retrieve the survey via id
            data_type: 'survey_subscribe' -> Returns the data just for the survey subscribe data
                        other -> Returns the Survey Serialized data
            pk: Stores either the survey url or the survey depending on the type
        :return: A serialized response with the survey that was retrieved
        """
        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Determine the method for getting the survey
        retrieve_type = self.request.query_params.get('type', None)
        data_type = self.request.query_params.get('data_type', None)

        # Retrieve the survey id/url
        pk = kwargs.pop('pk', None)

        client = get_object_or_404(MyUser, id=pk)

        surveys = RentingSurveyModel.objects.filter(user_profile=client.userProfile)

        serializer = RentSurveySerializer(surveys, context={'user': user_profile.user}, many=True)
        return Response(serializer.data)


class RentSurveyViewSet(mixins.RetrieveModelMixin, mixins.UpdateModelMixin, mixins.ListModelMixin,
                        mixins.CreateModelMixin, viewsets.GenericViewSet):

    serializer_class = RentSurveySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_permissions(self):
        """
        Dynamically get permissions because we only allow the user to not be authenticated on the
            create method
        """
        if self.action == 'create':
            permission_classes = [AllowAny]
        else:
            permission_classes = [IsAuthenticated]

        return [permission() for permission in permission_classes]

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        return retrieve_survey_queryset(user_profile)

    def list(self, request, *args, **kwargs):
        """
        When the surveys are being listed, only return the surveys that belong to the user.
        This is needed because the queryset if the user is an admin now includes all surveys,
            therefore when the list api is requested, just returns that users surveys
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        qs = RentingSurveyModel.objects.filter(user_profile=user_profile)
        serializer = RentSurveySerializer(qs, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        """
        Retrieves a survey based on either the id or the survey url
        :param request:
        :param args:
        :param kwargs:
            type: 'by_url' -> The survey is retrieved by using the survey url
                   other -> Anything else will default the request to retrieve the survey via id
            data_type: 'survey_subscribe' -> Returns the data just for the survey subscribe data
                        other -> Returns the Survey Serialized data
            pk: Stores either the survey url or the survey depending on the type
        :return: A serialized response with the survey that was retrieved
        """
        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Determine the method for getting the survey
        retrieve_type = self.request.query_params.get('type', None)
        data_type = self.request.query_params.get('data_type', None)

        # Retrieve the survey id/url
        pk = kwargs.pop('pk', None)

        if retrieve_type == 'by_url':
            # Retrieve the associated survey with the request
            survey = retrieve_survey(user_profile, url=pk)
        else:
            survey = retrieve_survey(user_profile, pk=pk)

        if data_type == 'survey_subscribe':
            serializer = SurveySubscribeSerializer(survey)
            return Response(serializer.data)
        else:
            serializer = RentSurveySerializer(survey, context={'user': user_profile.user})
            return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        """
        Retrieves all the data from the frontend
        Then the data is parsed to each of the sections
        If all the forms are valid, they are saved and the redirect url is returned
        Otherwise the form errors are returned
        :param request:
        :param args:
        :param kwargs:
        :return:
        """

        data = self.request.data['data']

        # Parse data to correct format
        survey_data = None
        tenant_data = None
        user_data = None

        # Save data if it exists
        if 'generalInfo' in data:
            survey_data = data['generalInfo']
        if 'amenitiesInfo' in data:
            survey_data.update(data['amenitiesInfo'])
        if 'tenantInfo' in data:
            tenant_data = data['tenantInfo']
        if 'detailsInfo' in data:
            user_data = data['detailsInfo']

        form = RentSurveyForm(survey_data)
        tenants = TenantFormSet(tenant_data)
        user_form = None

        user = self.request.user
        if user.is_anonymous():
            user = None
        user_signing_in = False

        # Determines if the user is trying to sign in or create a new account and creates
        #   the corresponding form
        if not self.request.user.is_authenticated():
            if user_data.get('user_logging_in', False):
                user_signing_in = True
                user_form_data = {
                    'username': user_data.get('email'),
                    'password': user_data.get('password1'),
                }
                user_form = LoginUserForm(request, user_form_data)
            else:
                user_form = ApartmentHunterSignupForm(user_data)

        # Determines if any of the forms is not valid, and only check user_form if it exists
        forms_valid = form.is_valid() and tenants.is_valid() and user_form.is_valid() if user_form is not None else True

        # Only bother checking if all the forms are valid and there is a user_form
        # Called after checking to see if all the forms are valid
        if forms_valid and user_form is not None:

cocoon/survey/templates/survey/helpers/address_form.html
<div id="form-group locationField">
    <label for="autocomplete">Address:</label>
    <br>
    <input id="autocomplete" placeholder="Enter your address" type="text">
    <br>
    <br>
</div>

<div class="form-group">
    {% comment %} Contains form for destination {% endcomment %}
    <div>

        <ul class="nav nav-tabs">
            <li id='form_destination_minus_span'><a><span  class="glyphicon glyphicon-minus" onclick="add_destination_form(-1,
                    {{ number_of_formsets }})"></span></a></li>
            {% for num_forms in form_destination %}
                <li
                        {% if forloop.counter == 1 %}
                            class="active"
                        {% elif forloop.counter <= number_of_destinations %}
                            class=""
                        {% else %}
                            class="hide"
                        {% endif %}
                            id="form_destination_tabs_{{ forloop.counter }}">

                    <a data-toggle="tab"
                       href="#form_destination_section_{{ forloop.counter }}"
                        onclick="clean_autocomplete()"><b>Commuter {{ forloop.counter }}</b></a></li>
            {% endfor %}
            <li
                    {% if number_of_destinations >= number_of_formsets %}
                        class='hide'
                    {% endif %}
                        id='form_destination_add_span'><a><span  class="glyphicon glyphicon-plus" onclick="add_destination_form(1,
                    {{ number_of_formsets }})"></span></a></li>
        </ul>
        <div id="form_destination_div" class="tab-content">
            {{ form.number_destinations_filled_out }}
            {{ form_destination.management_form }}
            {% for form in form_destination %}
                <div id="form_destination_section_{{ forloop.counter }}"
                        {% if forloop.counter == 1 %}
                     class="tab-pane fade in active">
                        {% else %}
                            class="tab-pane fade">
                        {% endif %}
                <br>
                {{ form.as_table }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

cocoon/survey/templates/survey/helpers/rent_survey_mini_form.html
<div id="sidebarSurvey" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <form action="{% url 'survey:rentSurveyResult' survey_id=survey.id %}" method="post">
        {{ form.non_field_errors }}
        {{ form.errors }}
        {% csrf_token %}
        <div class="form-group step_div">
            <div class="form-group">
                {{ form.name_survey.label_tag }}
                {{ form.name_survey }}
                {{ form.name_survey.errors }}
            </div>
            <div class="form-group">
                {{ form.num_bedrooms_survey.label_tag }}
                {{ form.num_bedrooms_survey }}
                {{ form.num_bedrooms_survey.errors }}
            </div>
            <div class="form-group">
                {{ form.home_type_survey.label_tag }}
                {{ form.home_type_survey }}
                {{ form.home_type_survey.errors }}
            </div>
            <div class="form-group">
                <label for="amountCost">Cost Per Month:</label>
                <input type="text" id="amountCost" name="amountCost" readonly
                       size="30" style="border:0; color:#f6931f; font-weight:bold;">
                <div id="cost"></div>
                {{ form.desired_price_survey }}
                {{ form.max_price_survey }}
            </div>
            <div class="form-group">
                {{ form.price_weight_survey.label_tag }}
                {{ form.price_weight_survey }}
                {{ form.price_weight_survey.errors }}
            </div>
            <br>
            {% include "survey/helpers/commuter_form.html" %}
            <br>
            <br>
        </div>
        <div class="form-group">
            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                Interior Amenities</a>
                        </h4>
                    </div>
                    <div id="collapse1" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <p>
                                {{ form.air_conditioning_survey.label_tag }}
                                {{ form.air_conditioning_survey }}
                                {{ form.air_conditioning_survey.errors }}
                            </p>

                            <p>
                                {{ form.interior_washer_dryer_survey.label_tag }}
                                {{ form.interior_washer_dryer_survey }}
                                {{ form.interior_washer_dryer_survey.errors }}
                            </p>

                            <p>
                                {{ form.dish_washer_survey.label_tag }}
                                {{ form.dish_washer_survey }}
                                {{ form.dish_washer_survey.errors }}
                            </p>

                            <p>
                                {{ form.bath_survey.label_tag }}
                                {{ form.bath_survey }}
                                {{ form.bath_survey.errors }}
                            </p>

                            <p>
                                <label for="amountBathrooms"># Bathrooms:</label>
                                <input type="text" id="amountBathrooms" name="amountBathrooms" readonly
                                       style="border:0; color:#f6931f; font-weight:bold;">
                            <div id="bathrooms"></div>
                            {{ form.min_bathrooms_survey }}
                            {{ form.max_bathrooms_survey }}
                            {{ form.min_bathrooms_survey.errors }}
                            {{ form.max_bathrooms_survey.errors }}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                Building/Exterior Amentities</a>
                        </h4>
                    </div>
                    <div id="collapse2" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p>
                                {{ form.parking_spot_survey.label_tag }}
                                {{ form.parking_spot_survey }}
                                {{ form.parking_spot_survey.errors }}
                            </p>
                            <p>
                                {{ form.building_washer_dryer_survey.label_tag }}
                                {{ form.building_washer_dryer_survey }}
                                {{ form.building_washer_dryer_survey.errors }}
                            </p>
                            <p>
                                {{ form.elevator_survey.label_tag }}
                                {{ form.elevator_survey }}
                                {{ form.elevator_survey.errors }}
                            </p>
                            <p>
                                {{ form.handicap_access_survey.label_tag }}
                                {{ form.handicap_access_survey }}
                                {{ form.handicap_access_survey.errors }}
                            </p>
                            <p>
                                {{ form.pool_hot_tub_survey.label_tag }}
                                {{ form.pool_hot_tub_survey }}
                                {{ form.pool_hot_tub_survey.errors }}
                            </p>
                            <p>
                                {{ form.fitness_center_survey.label_tag }}
                                {{ form.fitness_center_survey }}
                                {{ form.fitness_center_survey.errors }}
                            </p>
                            <p>
                                {{ form.storage_unit_survey.label_tag }}
                                {{ form.storage_unit_survey }}
                                {{ form.storage_unit_survey.errors }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" id="Submit" class="btn btn-primary">Submit Survey</button>
        </div>
    </form>
</div>