cocoon/commutes/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'commuteTypes', views.CommuteTypeViewSet, base_name='commute_types')

app_name = 'commutes'
urlpatterns = [
    # Api
    url(r'^api/', include(router.urls))
]

cocoon/frontend/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^react/', views.index),
]

cocoon/homePage/urls.py
from django.conf.urls import url

from . import views

app_name = 'homePage'
urlpatterns = [
    url(r'^$', views.LandingPage.as_view(), name='index'),
]

cocoon/scheduler/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'itinerary', views.ItineraryViewset, base_name='itinerary')
# router.register(r'visitTime', views.VisitTimeViewset, base_name='visitTime')
router.register(r'itineraryClient', views.ItineraryClientViewSet, base_name='itineraryClient')
router.register(r'itineraryAgent', views.ItineraryAgentViewSet, base_name='itineraryAgent')
router.register(r'itineraryMarket', views.ItineraryMarketViewSet, base_name='itineraryMarket')
router.register(r'itineraryDuration', views.ClientItineraryCalculateDuration, base_name='itineraryDuration')
router.register(r'itineraryClientStatus', views.RetrieveClientItineraryStatus, base_name='itineraryClientStatus')

app_name = 'scheduler'
urlpatterns = [
    url(r'^agentSchedulerPortal/', views.AgentSchedulerPortalView.as_view(), name="agentSchedulerPortal"),
    url(r'^agentSchedulerMarketplace/', views.AgentSchedulerMarketplaceView.as_view(), name="agentSchedulerMarketplace"),
    url(r'^clientScheduler', views.ClientSchedulerView.as_view(), name="clientScheduler"),
    url(r'^itineraryPage/(?P<itinerary_slug>.*)/$', views.ItineraryFileView.as_view(), name="itineraryFile"),

    # AJAX requests below
    url(r'^unscheduleItinerary/$', views.unschedule_itinerary, name="unscheduleItinerary"),
    url(r'^updateVisitTime/$', views.update_visit_time, name="updateVisitTime"),

    # Api
    url(r'^api/', include(router.urls))
]

cocoon/survey/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'rentSurvey', views.RentSurveyViewSet, base_name='user_survey')
router.register(r'rentSurveyAgent', views.RentSurveyAgentViewSet, base_name='user_survey_agent')
router.register(r'rentResult', views.RentResultViewSet, base_name='survey-result')
router.register(r'tenants', views.TenantViewSet, base_name='tenants-update')

app_name = 'survey'
urlpatterns = [
    url(r'^rent/$', views.RentingSurveyTemplate.as_view(), name="rentingSurvey"),
    url(r'^rent/(?P<survey_url>.*)/$', views.RentingResultTemplate.as_view(), name="rentSurveyResult"),

    # Api
    url(r'^api/', include(router.urls))
]

cocoon/userAuth/urls.py
from django.conf.urls import url, include

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'resendVerificationEmail', views.ResendVerificationEmail, base_name='userAuth-resend-verification')
router.register(r'agentClients', views.RetrieveClientsViewSet, base_name='userAuth-retrieve-clients')

app_name = 'userAuth'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.loginPage, name='loginPage'),
    # url(r'^register/$', views.SignUpView.as_view(), name='signup'),
    url(r'^register/hunter/', views.ApartmentHunterSignupView.as_view(), name='hunter_signup'),
    url(r'^register/broker/', views.BrokerSignupView.as_view(), name='broker_signup'),
    url(r'^password_change/$', views.change_password, name='change_password'),
    url(r'^logout/$', views.logoutPage, name='logoutPage'),
    url(r'^profile$', views.user_profile, name='user_profile'),
    url(r'^tourSetup/$', views.TourSetup.as_view(), name='tour_setup'),
    url(r'^myClients/$', views.MyClients.as_view(), name='my_clients'),

    # Email verification
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate_account, name='activateAccount'),
    url(r'^termsofuse', views.TermsOfUse.as_view(), name='terms_of_use'),

    # Api
    url(r'^api/', include(router.urls))
]

config/urls.py
from django.conf.urls import url, include, handler404
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

urlpatterns = [
    url(r'^adminBostoncocoon/', admin.site.urls),
    url(r'^', include('cocoon.homePage.urls')),
    url(r'^userAuth/', include('cocoon.userAuth.urls')),
    url(r'^houseDatabase/', include('cocoon.houseDatabase.urls')),
    url(r'^commutes/', include('cocoon.commutes.urls')),
    url(r'^survey/', include('cocoon.survey.urls')),
    url(r'^scheduler/', include('cocoon.scheduler.urls')),
    url(r'^signatures/', include('cocoon.signature.urls')),
    url(r'^password_reset/$', auth_views.password_reset,
        {
            'post_reset_redirect': reverse_lazy('password_reset_done'),
            'html_email_template_name': 'registration/password_reset_html_email.html'
        },
        name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'cocoon.views.error_404_view'

cocoon/homePage/forms.py
from django import forms


class SurveyType(forms.Form):
    SURVEY_TYPES = [
        ('rent', 'Rent'),
       # ('buy', 'Buy'),
    ]
    survey_type = forms.ChoiceField(
        choices=SURVEY_TYPES,
        widget=forms.RadioSelect()
    )

cocoon/commutes/views.py
# Import Rest Framework modules
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

# Import Cocoon Modules
from cocoon.commutes.serializers import CommuteTypeSerializer
from cocoon.commutes.models import CommuteType


class CommuteTypeViewSet(viewsets.ModelViewSet):
    """
    Returns all the commute types available to select
    """
    queryset = CommuteType.objects.all()
    serializer_class = CommuteTypeSerializer
    permission_classes = [AllowAny]

cocoon/dataAnalysis/views.py
from django.shortcuts import render

# Create your views here.

cocoon/homePage/views.py
# Django Modules
from django.views.generic import TemplateView


class LandingPage(TemplateView):

    template_name = "homePage/landingPage.html"


class AboutUs(TemplateView):

    template_name = "homePage/aboutUs.html"

cocoon/houseDatabase/views.py
# Import Rest Framework modules
from rest_framework import viewsets
from rest_framework.permissions import AllowAny

# Import Cocoon Modules
from cocoon.houseDatabase.serializers import HomeTypeSerializer
from cocoon.houseDatabase.models import HomeTypeModel


class HomeTypeViewSet(viewsets.ModelViewSet):
    """
    Returns all the home types available to select
    """
    queryset = HomeTypeModel.objects.all()
    serializer_class = HomeTypeSerializer
    permission_classes = [AllowAny]

cocoon/scheduler/views.py
# Django modules
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404
from django.contrib.sites.shortcuts import get_current_site

# App Models
from .models import ItineraryModel, TimeModel, ViableTourTimeModel, HomeVisitModel
from .serializers import ItinerarySerializer, ViableTourTimeSerializer
from .helpers.send_emails import send_new_itinerary_marketplace_email, send_new_itinerary_referred_email

# Cocoon Modules
from cocoon.userAuth.models import UserProfile, MyUser
from cocoon.survey.models import RentingSurveyModel
from cocoon.scheduler.models import ItineraryModel
from cocoon.scheduler.clientScheduler.client_scheduler import ClientScheduler
from cocoon.commutes.constants import CommuteAccuracy

# Python Modules
import json
from django.utils import dateparse
import datetime
import dateutil

# Rest Framework
from rest_framework import viewsets, mixins
from rest_framework.response import Response


@method_decorator(user_passes_test(lambda u: u.is_hunter or u.is_admin), name='dispatch')
class ItineraryFileView(TemplateView):
    """
    Loads the template for an individual itinerary
    """
    template_name = 'scheduler/itineraryFile.html'

    def dispatch(self, request, *args, **kwargs):
        itinerary_slug = kwargs.get('itinerary_slug')
        self.itinerary = get_object_or_404(ItineraryModel, url=itinerary_slug)
        self.tour_ordered_visits = [visit for visit in self.itinerary.ordered_homes.order_by("visit_index")]
        return super(ItineraryFileView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(TemplateView, self).get_context_data(**kwargs)

        m, _ = divmod(self.itinerary.tour_duration_seconds_rounded, 60)
        h, m = divmod(m, 60)
        friendly_duration = "{0}h {1}m".format(h, m)

        destinations = []
        if self.itinerary.survey:
            tenants = self.itinerary.survey.tenants
            for t in tenants.all():
                destinations.append(t.full_address)

        visit_times = [
            list(ViableTourTimeModel.objects.filter(home_visit=home_visit).order_by("visit_time").all()) for home_visit in self.tour_ordered_visits
        ]

        start_times = self.itinerary.start_times

        # Survey load url
        current_site = get_current_site(self.request)
        survey_load_url = "https://{0}/survey/rent/{1}/".format(current_site.domain, self.itinerary.survey.url)

        context.update({
            'client': self.itinerary.client,
            'survey': self.itinerary.survey,
            'destinations': destinations,
            'itinerary_claimed': False if self.itinerary.agent is None else True,
            'agent': self.itinerary.agent,
            'tour_duration': friendly_duration,
            'is_scheduled': False if self.itinerary.selected_start_time is None else True,
            'start_time': self.itinerary.selected_start_time,
            'home_visits': self.tour_ordered_visits,
            'is_finished': self.itinerary.finished,
            'visit_times': visit_times,
            "start_times": start_times,
            "survey_url": survey_load_url,
        })
        return context


@method_decorator(login_required, name='dispatch')
class ClientSchedulerView(TemplateView):
    """
    Loads the template for the ClientScheduler

    The template has the entry point for React and react handles
        the rest of the frontend
    """
    template_name = 'scheduler/clientScheduler.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        # Tells React which component to load onto the page
        data['component'] = ClientSchedulerView.__name__
        return data


@method_decorator(login_required, name='dispatch')
class AgentSchedulerPortalView(TemplateView):
    """
    Loads the template for the AgentSchedulerPortal

    The template contains the entry point for React and react handles
    retrieving the necessary data
    """
    template_name = 'scheduler/agentSchedulerPortal.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        # Tells React which component to load onto the page
        data['component'] = AgentSchedulerPortalView.__name__
        return data


@method_decorator(login_required, name='dispatch')
class AgentSchedulerMarketplaceView(TemplateView):
    """
        Loads the template for the AgentSchedulerMarketplace

        The template contains the entry point for React and react handles
        retrieving the necessary data
        """
    template_name = 'scheduler/agentSchedulerMarketplace.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        # Tells React which component to load onto the page
        data['component'] = AgentSchedulerMarketplaceView.__name__
        return data


class ItineraryViewset(viewsets.ReadOnlyModelViewSet):
    """
    Used for retrieving a generic itinerary. Base on the account type the user
    can get access to more itinerary models
    """

    serializer_class = ItinerarySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        if user_profile.user.is_broker or user_profile.user.is_admin:
            return ItineraryModel.objects.all()
        else:
            return ItineraryModel.objects.filter(client=user_profile.user)


@method_decorator(user_passes_test(lambda u: u.is_hunter or u.is_broker or u.is_admin), name='dispatch')
class ItineraryClientViewSet(viewsets.ModelViewSet):
    """
    Used on the client scheduler page to retrieve the itineraries for the current user
    """

    serializer_class = ItinerarySerializer

    def get_serializer_context(self):
        """
        Gets the context data for the serializer so that broker accounts get the information regarding
            the home
        """
        return {'user': self.request.user}

    def get_queryset(self):
        user_profile = get_object_or_404(UserProfile, user=self.request.user)
        return ItineraryModel.objects.filter(client=user_profile.user).filter(finished=False)

    def create(self, request, *args, **kwargs):
        """
        Creates an itinerary for a client. The survey id associated with the itinerary is passed in
            and the homes on that surveys visit list is added to the itinerary
        :param request:
        :param args:
        :param kwargs:
                Expects:
                    survey_id: (int) -> The id of the survey associated with the itinerary
        :return:
            {
                'results': (boolean) -> True: The itinerary was successfully created
                                        False: The itinerary was not successfully created
                'message': (string) -> A message related to the response
            }
        """
        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Retrieve the survey associated with the itinerary
        if 'survey_id' in self.request.data:
            survey_id = self.request.data['survey_id']
            survey = get_object_or_404(RentingSurveyModel, id=survey_id, user_profile=user_profile)
        else:
            raise Http404

        homes_list = []
        for home in survey.visit_list.all():
            homes_list.append(home)

        # Run client_scheduler algorithm
        client_scheduler_alg = ClientScheduler(CommuteAccuracy.EXACT)
        result = client_scheduler_alg.save_itinerary(homes_list, self.request.user, survey)
        if result:
            return Response({
                'result': True,
                'message': 'Itinerary created'
            })
        else:
            return Response({
                'result': False,
                'message': 'Failed to created itinerary'
            })

    def update(self, request, *args, **kwargs):

        # Retrieve the user profile
        user_profile = get_object_or_404(UserProfile, user=self.request.user)

        # Retrieve the itinerary id
        pk = kwargs.pop('pk', None)

        # Retrieve the associated itinerary with the request
        itinerary = get_object_or_404(ItineraryModel, pk=pk, client=user_profile.user)

        # Save all the available start times the client indicated
        if 'start_times' in self.request.data['type']:
            start_times = self.request.data['start_times']

            # Loop through all the start_times so they can all be added
            for start_time in start_times:
                if 'time_available_seconds' in start_time:
                    time_available_seconds = start_time['time_available_seconds']
                    dt = dateutil.parser.parse(start_time['date'])
                    dt = dt.replace(second=0, microsecond=0)
                    itinerary.start_times.create(time=dt, time_available_seconds=time_available_seconds)

            # Generate potential visit times so agents can coordinate with property managers
            client_scheduler_alg = ClientScheduler(CommuteAccuracy.EXACT)
            client_scheduler_alg.generate_tour_times(user=user_profile.user)

            # Automatically set the agent assigned to the itinerary if the agent has a referred agent
            # Send an email to the appropriate people
            if user_profile.referred_agent is not None:

cocoon/templates/base.html
{% load static %}
{% load intercom %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} Cocoon {% endblock %}</title>
    <!-- JQuery CDN -->
    <script
            src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous"></script>
    <!-- Font Styles -->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600,700,800" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="theme-color" content="#A13718" />
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.0-custom/css/bootstrap.css' %}">
    <link href="{% static 'cocoon/main/css/base.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'homePage/cocoon_logo.png' %}"/>
{% block head %}

{% endblock %}
</head>
<body>

{% block nav_bar %}
    <nav>
        <div class="logo">
            <a href="{% url 'homePage:index' %}">
                <img src="{% static 'homePage/cocoon-logo_beta.png' %}" alt="">
            </a>
        </div>

        <div class="nav-links_desktop">

            {% comment %}Unauthorized Links{% endcomment %}
            {% if not user.is_authenticated %}

                <div>
                    <a href="{% url 'userAuth:loginPage' %}">Login</a>
                    <span>/</span>
                    <a href="{% url 'userAuth:hunter_signup' %}" class="redOrange">Sign Up</a>
                </div>

            {% else %}
                {% comment %}Authorized Links{% endcomment %}
                <div>
                    {% if user.is_hunter %}
                        <a href="{% url 'userAuth:tour_setup' %}">Tour Setup</a>
                    {% endif %}
                    <span>/</span>
                    {% if user.is_broker %}
                        <a href="{% url 'userAuth:my_clients' %}">My Clients</a>
                    {% endif %}
                    <span>/</span>
                    <a href="{% url 'scheduler:clientScheduler' %}">My Itinerary</a>
                    <span>/</span>
                    {% if user.is_broker or user.is_admin %}
                        <a href="{% url 'scheduler:agentSchedulerPortal' %}">Agent Portal</a>
                        <span>/</span>
                        <a href="{% url 'scheduler:agentSchedulerMarketplace' %}">Marketplace</a>
                        <span>/</span>
                    {% endif %}
                    <div id="dropdown">
                        <button>{{ user.email }} <i class="material-icons">arrow_drop_down</i></button>
                        <div class="dropdown-content">
                            <a href="{% url 'userAuth:user_profile' %}">Profile</a>
                            <a href="{% url 'userAuth:logoutPage' %}">Logout</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>

        {% comment %}Mobile Nav{% endcomment %}
        <div class="nav-links_mobile">
            <div class="hamburger-menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

    </nav>
    <div class="mobile-links">
        {% if not user.is_authenticated %}
            <a href="{% url 'userAuth:loginPage' %}">Login</a>
            <a href="{% url 'userAuth:hunter_signup' %}">Sign Up</a>
        {% else %}
            <a href="{% url 'userAuth:tour_setup' %}">Tour Setup</a>
            <a href="{% url 'scheduler:clientScheduler' %}">My Itinerary</a>
            {% if user.is_broker or user.is_admin%}
                <a href="{% url 'scheduler:agentSchedulerPortal' %}">Agent Portal</a>
                <a href="{% url 'scheduler:agentSchedulerMarketplace' %}">Marketplace</a>
            {% endif %}
            <a href="{% url 'userAuth:user_profile' %}">Profile</a>
            <a href="{% url 'userAuth:logoutPage' %}">Logout</a>
        {% endif %}
    </div>
    {% comment %}END OF HEADER & NAV MENUS{% endcomment %}
{% endblock nav_bar %}

<div id="siteWrapper" class="{% block container_type %}container{% endblock %}">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible message_timeout" role="alert" style="text-align: center; margin-bottom: 0">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

    <div id="siteWrapper">

    {% block content %}{% endblock %}

    </div>

</div>
{% block endScripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'bootstrap-3.4.0-custom/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'cocoon/main/js/base.js' %}"></script>
    <script src="{% static 'cocoon/main/js/navbar.js' %}"></script>
{% endblock %}
{% block footer %}
    <footer>
        <div class="container">
            <p>All rights reserved. Cocoon © 2019</p>
        </div>
    </footer>
{% endblock %}
{% intercom_tag %}
</body>
</html>

cocoon/templates/base_email_button.html
{% extends "base_email.html" %}

{% block buttonSection %}
    <tr>
        <td align="center" vertical-align="middle"
            style="font-size:0px;padding:10px 25px;word-break:break-word;">
            <table border="0" cellpadding="0" cellspacing="0" role="presentation"
                   style="border-collapse:separate;width:100%;line-height:100%;">
                <tr>
                    <td align="center" bgcolor="#a13718" role="presentation"
                        style="border:none;border-radius:10px;cursor:auto;padding:15px 25px;background:#a13718;"
                        valign="middle">
                        <a href="{% block buttonLink %}{% endblock %}"
                           style="background:#a13718;color:#ffffff;font-family:Montserrat, sans-serif;font-size:15px;font-weight:bold;line-height:120%;Margin:0;text-decoration:none;text-transform:none;"
                           target="_blank">{% block buttonText %}{% endblock %}</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
{% endblock %}